build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related PROD APIs"
  contactDetails:
    name: "Nguyen Thi Thu Ngoc - Owner"
    email: "ngocnguyen@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345