build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "Dau Minh Phuc - Developer"
    email: "minhphuc@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345