spring:
  application:
    name: "configserver"
  profiles:
    active: git
#      active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/daduc1-microservice/configserver.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths:
            - /src/main/resources/config
#        native:
#          search-locations: "classpath:/config"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "ZGF1IGFuaCBkdWM="

server:
  port: 8071
